/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariana
 */
public class FirstFrame extends javax.swing.JFrame {

    static Bank bank= new Bank();
    static WriteFile obj=new WriteFile();
    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        savingAccount = new javax.swing.JButton();
        spendingAccount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        deactivateAccount = new javax.swing.JButton();
        activateAccount = new javax.swing.JButton();
        createAcc = new javax.swing.JButton();
        exit = new javax.swing.JToggleButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 48)); // NOI18N
        jLabel1.setText(" WELCOME! ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 3, 1, 3, new java.awt.Color(102, 255, 102)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Access your:");

        savingAccount.setText("Saving Account");
        savingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAccountActionPerformed(evt);
            }
        });

        spendingAccount.setText("Spending Account");
        spendingAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spendingAccountActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Enter your PIN:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("You have no account?");

        deactivateAccount.setText("Deactivate Account");
        deactivateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateAccountActionPerformed(evt);
            }
        });

        activateAccount.setText("Activate Account");
        activateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateAccountActionPerformed(evt);
            }
        });

        createAcc.setText("Create one!!");
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(createAcc)))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deactivateAccount))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savingAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spendingAccount))
                                .addGap(234, 234, 234)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passField))
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(activateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(savingAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spendingAccount))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deactivateAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(activateAccount)
                .addGap(42, 42, 42)
                .addComponent(exit)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAccountActionPerformed
        // TODO add your handling code here:
        String password=passField.getText();
        if(bank.searchByPIN(password)){
            if(bank.notDeactivate(password)){
             
              String res=bank.searchTypeAcc(password);
              //JOptionPane.showMessageDialog(null,res) ;
              if(res.equals("SavingAccount")){
                   bank.setActiveAccount(password);
                    new SavingAccFrame().setVisible(true);
              }
              else
                    JOptionPane.showMessageDialog(null,"This Saving Account doesn't exist or you taped a wrong password!","Warning",1) ;
            }
            else
                JOptionPane.showMessageDialog(null,"You have deactivated your account!","Warning",2) ;
        }
        else
            JOptionPane.showMessageDialog(null,"This Saving Account doesn't exist or you taped a wrong password!","Warning",1) ;
        
    }//GEN-LAST:event_savingAccountActionPerformed

    private void spendingAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spendingAccountActionPerformed
        // TODO add your handling code here:
        String password=passField.getText();
        if(bank.searchByPIN(password)){
            if(bank.notDeactivate(password)){
                 if(bank.searchTypeAcc(password).equals("SpendingAccount")){
                     bank.setActiveAccount(password);
                     new SpendingAccFrame().setVisible(true); 
                 }
                 else
                     JOptionPane.showMessageDialog(null,"This Spending Account doesn't exist or you taped a wrong password!","Warning",1) ;
            }
            else
                JOptionPane.showMessageDialog(null,"You have deactivated your account!","Warning",2) ;
        }
        else
             JOptionPane.showMessageDialog(null,"This Saving Account doesn't exist or you taped a wrong password!","Warning",1) ;
    }//GEN-LAST:event_spendingAccountActionPerformed

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed
        // TODO add your handling code here:
        new CreateAccFrame().setVisible(true);
    }//GEN-LAST:event_createAccActionPerformed

    private void deactivateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateAccountActionPerformed
        // TODO add your handling code here:
        String pass=passField.getText();
        if(pass.isEmpty())
            JOptionPane.showMessageDialog(null,"Introduce your password!","Warning",2) ;
        bank.deactivateAccount(pass);
        JOptionPane.showMessageDialog(null,"Your account was deactivated!","",1) ;
    }//GEN-LAST:event_deactivateAccountActionPerformed

    private void activateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateAccountActionPerformed
        // TODO add your handling code here:
        String pass=passField.getText();
        if(pass.isEmpty())
            JOptionPane.showMessageDialog(null,"Introduce your password!","Warning",2) ;
        bank.activateAccount(pass);
        JOptionPane.showMessageDialog(null,"Your account was reactivated!","",1) ;
    }//GEN-LAST:event_activateAccountActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        obj.save();
        close();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateAccount;
    private javax.swing.JButton createAcc;
    private javax.swing.JButton deactivateAccount;
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton savingAccount;
    private javax.swing.JButton spendingAccount;
    // End of variables declaration//GEN-END:variables
}
