/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tema4;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ariana
 */
public class SavingAccFrame extends javax.swing.JFrame {
    static Bank bank=new Bank();
    /**
     * Creates new form SavingAccFrame
     */
    public SavingAccFrame() {
        initComponents();
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        balance = new javax.swing.JButton();
        getCash = new javax.swing.JButton();
        depoCash = new javax.swing.JButton();
        hundred = new javax.swing.JRadioButton();
        fifty = new javax.swing.JRadioButton();
        fivehundred = new javax.swing.JRadioButton();
        thousand = new javax.swing.JRadioButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Saving Account");

        balance.setText("Check my Balance");
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        getCash.setText("Get Cash");
        getCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getCashActionPerformed(evt);
            }
        });

        depoCash.setText("Deposit Cash");
        depoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depoCashActionPerformed(evt);
            }
        });

        buttonGroup1.add(hundred);
        hundred.setText("100");

        buttonGroup1.add(fifty);
        fifty.setText("50");

        buttonGroup1.add(fivehundred);
        fivehundred.setText("500");

        buttonGroup1.add(thousand);
        thousand.setText("1000");

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balance)
                    .addComponent(jLabel1)
                    .addComponent(getCash, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depoCash, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hundred)
                    .addComponent(fifty)
                    .addComponent(fivehundred)
                    .addComponent(thousand))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(balance)
                        .addGap(18, 18, 18)
                        .addComponent(getCash)
                        .addGap(18, 18, 18)
                        .addComponent(depoCash)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fifty)
                        .addGap(18, 18, 18)
                        .addComponent(hundred)
                        .addGap(18, 18, 18)
                        .addComponent(fivehundred)
                        .addGap(22, 22, 22)))
                .addComponent(thousand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
        bank.showBalance();
    }//GEN-LAST:event_balanceActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_exitActionPerformed

    private void getCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getCashActionPerformed
        // TODO add your handling code here:
        int a=0;
        if(fifty.isSelected())
            a=50;
        else
            if(hundred.isSelected())
                a=100;
             else
                if(fivehundred.isSelected())
                     a=500;
                else
                    if(thousand.isSelected())
                        a=1000;
        
        bank.extractMoney(a);
        JOptionPane.showMessageDialog(null,"Succes!");
    }//GEN-LAST:event_getCashActionPerformed

    private void depoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depoCashActionPerformed
        // TODO add your handling code here:
        int a=0;
        if(fifty.isSelected())
            a=50;
        else
            if(hundred.isSelected())
                a=100;
             else
                if(fivehundred.isSelected())
                     a=500;
                else
                    if(thousand.isSelected())
                        a=1000;
        
        bank.depositMoney(a);
        
    }//GEN-LAST:event_depoCashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavingAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavingAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavingAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavingAccFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SavingAccFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balance;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton depoCash;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fifty;
    private javax.swing.JRadioButton fivehundred;
    private javax.swing.JButton getCash;
    private javax.swing.JRadioButton hundred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton thousand;
    // End of variables declaration//GEN-END:variables
}
